version: '3'

services:
  app:
    container_name: flask_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/opt/api
    tty: true
    ports:
      - 5000:5000
    environment:
      TZ: Asia/Tokyo
      PYTHONPATH: /opt/api
      PORT: 5000
    # TODO: hot reload in development
    command: sh -c "pip3 install --upgrade -r /opt/api/requirements.txt && gunicorn --bind 0.0.0.0:5000 wsgi"
